### ISSUE TITLE
No schedule data except DEF CON?

### ISSUE THREAD

**Issue by mauvehed** [Advice-Dog/HackerTracker#1]
When filtering data under the Schedule, to anything except DEF CON, I don't see anything. Is this just not populated yet?

**Comment by Advice-Dog** [comment]
We're fetching the data directly from DEF CON, and that's what we have so far. 
https://info.defcon.org/json/schedule-full.json

I believe we'll start seeing more things pop up soon.

**Comment by mauvehed** [comment]
May be worth adding an Update on the Home page that clarifies this? I thought my app was broken for a while.

**Comment by Advice-Dog** [comment]
In the newest version (beta.6) there is a pull to refresh on the schedule screen. I was thinking maybe adding a little message informing people they could do that, would that help? I'm trying to think of a better way to let people know they're up to date, and all that jazz.

There is also automatic syncing options I'll be enabling when we get closer to the con.

**Comment by Advice-Dog** [comment]
@mauvehed 
What if I added text on the home screen letting people know how up to date their app is? Just some simple text saying "Last updated July 25th". Do you think that would help?

**Comment by mauvehed** [comment]
@Advice-Dog yeah something like that would be good, assuming that if you fall behind and this is expected, that it doesn't add confusion. You may also want to default the Filters on the Schedule to all being ON. I think they come OFF and I initially thought my app was busted because there was no data, and none of the filters except DEF CON had anything associated with them.

**Comment by Advice-Dog** [comment]
@mauvehed I just pushed out a new version with a few changes and I think it'll address all the problems. There is now a very clear indication of when the last sync was, filters are now all enabled by default showing everything, and pull down shows an alert to inform you of how the sync went.

**Comment by mauvehed** [comment]
That is awesome! Looks very clear now!
