### ISSUE TITLE
Ensure specified Google Material symbols are available

### ISSUE THREAD

**Issue by aNullValue** [Advice-Dog/HackerTracker#17]

**Comment by aNullValue** [comment]
SELECT DISTINCT google_materialsymbol
FROM conf.menu_item
ORDER BY google_materialsymbol

>>>>>

balance
calendar_month
description
directions_bus
directions_walk
door_open
escalator_warning
flag
groups
help
location_city
location_on
map
medical_mask
menu
news
point_of_sale
question_mark
restaurant_menu
search
shopping_bag
sprint
tv
wallpaper_slideshow

**Comment by Advice-Dog** [comment]
Done and done.
