### ISSUE TITLE
Fix app manifest for deep links

### ISSUE THREAD

**Issue by aNullValue** [Advice-Dog/HackerTracker#18]
In AndroidManifest.xml, the [definition](https://github.com/junctor/android/blob/74b0b0bfd6c12fbaf87f8714b0a8e4b2bb4eca9c/app/src/main/AndroidManifest.xml#L40-L43) for info.defcon.org specifies both HTTP and HTTPS in the same intent-filter. This is causing deep links to be disabled for info.defcon.org because the HTTP scheme is not available. Please remove the HTTP scheme.

Also, the [definition](https://github.com/junctor/android/blob/74b0b0bfd6c12fbaf87f8714b0a8e4b2bb4eca9c/app/src/main/AndroidManifest.xml#L52-L54) for hackertracker.app is not valid, as it specifies www.hackertracker.app, which does not exist (there should be no www). Also, the pathPrefix should be removed, since hackertracker.app does not use "/event".

**Comment by Advice-Dog** [comment]
https://github.com/junctor/android/commit/92e63e1ea30985056aaf164efb85c7e4b1d2393e
