### ISSUE TITLE
Events are automatically being bookmarked

### ISSUE THREAD

**Issue by zer0zer0133** [Advice-Dog/HackerTracker#19]
Events are automatically being bookmarked.
I tried to un-bookmark it, but it will automatically be bookmarked again.

Examples of specific events being bookmaked:
Hacker Summer Camp Parties: Aug 6, 6pm armis
Hacker Summer Camp Parties: Aug 7, 5pm cyberonesecurity
BSidesLV: Aug 7, 2pm Quantum Computing
BSidesLV: Aug 7, 2:30 One Port to Serve Them All
DEFCON32: Aug 8, 2pm Long Live Empire
DEFCON32: Aug 9, 10am Does the World Need Another Threat Model
and more...

I have tried clearing cache/data in my phone setting.
I have also uninstall and reinstall the app.

After re-install the app, I see a different set of events being automatically bookmarked,

Android
Version 7.2.4 (413)

**Comment by chrisporter-ah** [comment]
When are these events bookmarked? After a fresh install, are they already bookmarked or is it after any sort of interaction? How are you using the app to browse events and notice they are bookmarked?

**Comment by Advice-Dog** [comment]
edit: Sorry, replied from the wrong account. 

When you say these events are being bookmarked, when does it happen? Is it right away or after certain interactions? How are you browsing the events and noticing them being bookmarked?

There is some extra logic around bookmarking that could cause this to happen.

**Comment by zer0zer0133** [comment]
I never bookmarked these specific events that are auto-added.

Starting from after I uninstall and reinstall the app. It is in a clean slate with nothing bookmarked.
I would browse to DEFCON for example and look for sessions that I am interested in and start bookmarking them. Let's say I book mark session A, B, and C.

As I continue to scroll thru the big list of sessions, I will then notice session X, Y, Z are now bookmarked. 
I had never clicked into these and not bookmarked these.

I would go into session X to the description page, un-bookmark it, exit out of session X description page and in the big list of events, session X would be bookmarked again.

**Comment by Advice-Dog** [comment]
Thanks for the details! 

After looking more into it, I believe it's due to some sessions and content sharing ids, ie: content in the Hacker Summer Camp Parties with the same id as an event in DEF CON 32.

https://github.com/junctor/android/commit/4799ba312238c821ed74267cdce8e26328882f29

It should be fixed in the next update.
